name: Manually trigger a pipeline to test how GITUB_PATH works

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: dbg1
      run: |
        ./test1.sh
        ./test2.sh
    - name: dbg2
      run: |
        ./test2.sh

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: dbg3
      run: |
        ./test2.sh

